 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/pituku-submission-frontend:$COMMIT_SHA', '.', '--build-arg', 'REACT_APP_API_URL=${_REACT_APP_API_URL}']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'asia.gcr.io/$PROJECT_ID/pituku-submission-frontend:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'pituku-submission-frontend'
   - '--image'
   - 'asia.gcr.io/$PROJECT_ID/pituku-submission-frontend:$COMMIT_SHA'
   - '--region'
   - 'asia-southeast2'
 images:
 - 'asia.gcr.io/$PROJECT_ID/pituku-submission-frontend:$COMMIT_SHA'